/* Prototypes of imported library functions and data. */
#pragma once

double log10(double __x);
int intrflush(void * p0, int p1);
int fileno(FILE_2 * __stream);
int dup2(int __fd, int __fd2);
int nodelay(void * p0, int p1);
char * __stpcpy_chk(char * p0, char * p1, ulong p2);
char * strcasestr(char * __haystack, char * __needle);
char * dlerror(void);
int nl_socket_modify_cb(void * p0, int p1, int p2, void * p3, void * p4);
void * memset(void * __s, int __c, size_t __n);
int mvcur(int p0, int p1, int p2, int p3);
int snprintf(char * __s, size_t __maxlen, char * __format, ...);
int waddch(void * p0, uint p1);
int init_pair(short p0, short p1, short p2);
int backtrace(void * * p0, int p1);
int close(int __fd);
noreturn void abort(void);
char * stpcpy(char * __dest, char * __src);
int nonl(void);
int clock_gettime(clockid_t __clock_id, timespec_2 * __tp);
char * nl_langinfo(nl_item __item);
int __fprintf_chk(void * p0, int p1, char * p2, ...);
int uname(utsname * __name);
int fseek(FILE_2 * __stream, long __off, int __whence);
int select(int __nfds, fd_set * __readfds, fd_set * __writefds, fd_set * __exceptfds, timeval * __timeout);
int nl_recvmsgs_default(void * p0);
noreturn void exit(int __status);
int fstat(int __fd, stat_2 * __buf);
int __printf_chk(int p0, char * p1, ...);
int noecho(void);
int sched_setscheduler(__pid_t __pid, int __policy, sched_param_2 * __param);
int openat(int __fd, char * __file, int __oflag, ...);
int genlmsg_parse(void * p0, int p1, void * * p2, int p3, void * p4);
int putchar(int __c);
int keypad(void * p0, int p1);
char * strsignal(int __sig);
void * nl_socket_alloc(void);
int nl_connect(void * p0, int p1);
int strncmp(char * __s1, char * __s2, size_t __n);
void * malloc(size_t __size);
FILE_2 * fopen(char * __filename, char * __modes);
int getpriority(__priority_which_t __which, id_t __who);
int tputs(char * p0, int p1, void * p2);
int execlp(char * __file, char * __arg, ...);
int unlink(char * __name);
int nl_send_sync(void * p0, void * p1);
int curs_set(int p0);
noreturn void _exit(int __status);
void * __memcpy_chk(void * p0, void * p1, ulong p2, ulong p3);
int __isoc23_fscanf(void * p0, char * p1, ...);
int wmove(void * p0, int p1, int p2);
long sysconf(int __name);
int nla_put_u32(void * p0, int p1, uint p2);
char * strchrnul(char * __s, int __c);
int use_default_colors(void);
char * fgets(char * __s, int __n, FILE_2 * __stream);
int __vsnprintf_chk(char * p0, ulong p1, int p2, ulong p3, char * p4, void * p5);
void nlmsg_free(void * p0);
passwd * getpwuid(__uid_t __uid);
int whline(void * p0, uint p1, int p2);
__uid_t geteuid(void);
int wadd_wch(void * p0, void * p1);
int fputc(int __c, FILE_2 * __stream);
long lround(double __x);
void free(void * __ptr);
int sched_getscheduler(__pid_t __pid);
size_t strlen(char * __s);
int waddnstr(void * p0, char * p1, int p2);
int ferror(FILE_2 * __stream);
DIR_2 * opendir(char * __name);
ushort * * __ctype_b_loc(void);
int wattr_on(void * p0, uint p1, void * p2);
void * nla_data(void * p0);
int wrefresh(void * p0);
long __read_chk(int p0, void * p1, ulong p2, ulong p3);
dirent * readdir(DIR_2 * __dirp);
ssize_t readlinkat(int __fd, char * __path, char * __buf, size_t __len);
int wclear(void * p0);
int statfs(char * __file, statfs_2 * __buf);
int nocbreak(void);
size_t mbstowcs(int * __pwcs, char * __s, size_t __n);
void nl_close(void * p0);
FILE_2 * fdopen(int __fd, char * __modes);
char * strrchr(char * __s, int __c);
long syscall(long __sysno, ...);
int wadd_wchnstr(void * p0, void * p1, int p2);
char * strtok_r(char * __s, char * __delim, char * * __save_ptr);
int pipe(int * __pipedes);
int setpriority(__priority_which_t __which, id_t __who, int __prio);
int beep(void);
ulong mousemask(ulong p0, ulong * p1);
int kill(__pid_t __pid, int __sig);
void * initscr(void);
char * strerror(int __errnum);
char * strstr(char * __haystack, char * __needle);
int halfdelay(int p0);
int sigaction(int __sig, sigaction_2 * __act, sigaction_2 * __oact);
ulong __mbstowcs_chk(int * p0, char * p1, ulong p2, ulong p3);
void * dlopen(char * p0, int p1);
int fputs(char * __s, FILE_2 * __stream);
ssize_t readlink(char * __path, char * __buf, size_t __len);
int set_escdelay(int p0);
int dirfd(DIR_2 * __dirp);
int __isoc23_sscanf(char * p0, char * p1, ...);
int gethostname(char * __name, size_t __len);
int sched_getaffinity(__pid_t __pid, size_t __cpusetsize, cpu_set_t * __cpuset);
int wgetch(void * p0);
int raise(int __sig);
__sighandler_t_2 signal(int __sig, __sighandler_t_2 __handler);
void * memmove(void * __dest, void * __src, size_t __n);
char * strchr(char * __s, int __c);
__pid_t waitpid(__pid_t __pid, int * __stat_loc, int __options);
int ffsl(long __l);
void * nla_next(void * p0, int * p1);
int getopt_long(int p0, char * * p1, char * p2, void * p3, int * p4);
size_t fread(void * __ptr, size_t __size, size_t __n, FILE_2 * __stream);
ulong __isoc23_strtoull(char * p0, char * * p1, int p2);
char * getenv(char * __name);
long __isoc23_strtoll(char * p0, char * * p1, int p2);
int __libc_current_sigrtmax(void);
int * __errno_location(void);
void qsort(void * __base, size_t __nmemb, size_t __size, __compar_fn_t_2 __compar);
char * strdup(char * __s);
int endwin(void);
int wattrset(void * p0, int p1);
int mkstemp(char * __template);
int strncasecmp(char * __s1, char * __s2, size_t __n);
noreturn undefined __stack_chk_fail(void);
int strcmp(char * __s1, char * __s2);
void * __memset_chk(void * p0, int p1, ulong p2, ulong p3);
ulong __fread_chk(void * p0, ulong p1, ulong p2, ulong p3, void * p4);
int wcwidth(int __c);
long __isoc23_strtol(char * p0, char * * p1, int p2);
int genl_ctrl_resolve(void * p0, char * p1);
int nanosleep(timespec_2 * __requested_time, timespec_2 * __remaining);
int wvline(void * p0, uint p1, int p2);
__uid_t getuid(void);
int start_color(void);
void * calloc(size_t __nmemb, size_t __size);
int feof(FILE_2 * __stream);
void backtrace_symbols_fd(void * * p0, int p1, int p2);
int faccessat(int __fd, char * __file, int __type, int __flag);
int fclose(FILE_2 * __stream);
int statvfs(char * __file, statvfs_2 * __buf);
int cbreak(void);
void * nlmsg_hdr(void * p0);
char * strncpy(char * __dest, char * __src, size_t __n);
tm_2 * localtime_r(time_t * __timer, tm_2 * __tp);
int __libc_current_sigrtmin(void);
int mouseinterval(int p0);
int closedir(DIR_2 * __dirp);
wint_t btowc(int __c);
int sched_get_priority_max(int __algorithm);
int define_key(char * p0, int p1);
int __snprintf_chk(char * p0, ulong p1, int p2, ulong p3, char * p4, ...);
char * strsep(char * * __stringp, char * __delim);
int access(char * __name, int __type);
__pid_t fork(void);
int sigemptyset(sigset_t * __set);
void * dlsym(void * p0, char * p1);
int getmouse(void * p0);
void * realloc(void * __ptr, size_t __size);
int lstat(char * __file, stat_2 * __buf);
char * setlocale(int __category, char * __locale);
void * genlmsg_put(void * p0, uint p1, uint p2, int p3, int p4, int p5, uchar p6, uchar p7);
int rand(void);
int napms(int p0);
void * __memmove_chk(void * p0, void * p1, ulong p2, ulong p3);
ulong __isoc23_strtoul(char * p0, char * * p1, int p2);
long __libc_start_main();
ssize_t write(int __fd, void * __buf, size_t __n);
int sched_get_priority_min(int __algorithm);
void nl_socket_free(void * p0);
size_t strftime(char * __s, size_t __maxsize, char * __format, tm_2 * __tp);
int wattr_off(void * p0, uint p1, void * p2);
int stat(char * __file, stat_2 * __buf);
char * __fgets_chk(char * p0, ulong p1, int p2, void * p3);
double pow(double __x, double __y);
int fstatat(int __fd, char * __file, stat_2 * __buf, int __flag);
void * memcpy(void * __dest, void * __src, size_t __n);
int fcntl(int __fd, int __cmd, ...);
void * nlmsg_alloc(void);
int open(char * __file, int __oflag, ...);
int iswprint(wint_t __wc);
int __vasprintf_chk(char * * p0, int p1, char * p2, void * p3);
passwd * getpwnam(char * __name);
char * __strncat_chk(char * p0, char * p1, ulong p2, ulong p3);
int rename(char * __old, char * __new);
int has_colors(void);
int sched_setaffinity(__pid_t __pid, size_t __cpusetsize, cpu_set_t * __cpuset);
char * strndup(char * __string, size_t __n);
long __fdelt_chk(long p0);
int mkdir(char * __path, __mode_t __mode);
time_t time(time_t * __timer);
int fflush(FILE_2 * __stream);
DIR_2 * fdopendir(int __fd);
int dlclose(void * p0);
long __cxa_finalize();
long _ITM_deregisterTMCloneTable();
long _ITM_registerTMCloneTable();
long __gmon_start__();
extern void *stdscr;
#define _stdscr stdscr
extern void *cur_term;
#define _cur_term cur_term
extern int COLS;
#define _COLS COLS
extern int LINES;
#define _LINES LINES
extern int COLORS;
#define _COLORS COLORS
extern void *stderr;
#define _stderr stderr
extern void *stdout;
#define _stdout stdout
extern char *optarg;
#define _optarg optarg
extern int optind;
#define _optind optind
