/* Prototypes of all decompiled functions. */
#pragma once

typedef char _func__Bool_StrBuf_state_ptr_char;
typedef char _func_sd_bus_ptr_sd_bus_ptr;
typedef char _func_sensors_chip_name_ptr_sensors_chip_name_ptr_wchar_t_ptr;
typedef char _func_sensors_feature_ptr_sensors_chip_name_ptr_wchar_t_ptr;
typedef char _func_sensors_subfeature_ptr_sensors_chip_name_ptr_sensors_feature_ptr_sensors_subfeature_type;
typedef char _func_void;
typedef char _func_wchar_t_FILE_ptr;
typedef char _func_wchar_t_sd_bus_ptr_char_ptr_char_ptr_char_ptr_char_ptr_sd_bus_error_ptr_char_ptr_ptr;
typedef char _func_wchar_t_sd_bus_ptr_char_ptr_char_ptr_char_ptr_char_ptr_sd_bus_error_ptr_char_void_ptr;
typedef char _func_wchar_t_sd_bus_ptr_ptr;
typedef char _func_wchar_t_sensors_chip_name_ptr_wchar_t_double_ptr;

int main(int argc,char **argv);
void tagAllChildren(Panel *panel,Row *parent);
Htop_Reaction actionSortByPID(State_2 *st);
Htop_Reaction actionSortByMemory(State_2 *st);
Htop_Reaction actionSortByCPU(State_2 *st);
Htop_Reaction actionSortByTime(State_2 *st);
Htop_Reaction actionToggleRunningInContainer(State_2 *st);
Htop_Reaction actionToggleProgramPath(State_2 *st);
Htop_Reaction actionToggleMergedCommand(State_2 *st);
Htop_Reaction actionToggleTreeView(State_2 *st);
Htop_Reaction actionToggleHideMeters(State_2 *st);
Htop_Reaction actionInvertSortOrder(State_2 *st);
Htop_Reaction actionExpandOrCollapse(State_2 *st);
Htop_Reaction actionCollapseIntoParent(State_2 *st);
Htop_Reaction actionNextScreen(State_2 *st);
Htop_Reaction actionPrevScreen(State_2 *st);
Htop_Reaction actionQuit(State_2 *st);
Htop_Reaction Action_follow(State_2 *st);
Htop_Reaction actionTag(State_2 *st);
Htop_Reaction actionTogglePauseUpdate(State_2 *st);
Htop_Reaction actionUntagAll(State_2 *st);
Htop_Reaction actionTagAllChildren(State_2 *st);
void DynamicMeter_init(Meter_3 *meter);
void AllCPUsMeter_updateValues(Meter *this);
void CPUMeterCommonDraw(Meter *this,int x,int y,int w,int ncol);
void DualColCPUsMeter_draw(Meter *this,int x,int y,int w);
void QuadColCPUsMeter_draw(Meter *this,int x,int y,int w);
void OctoColCPUsMeter_draw(Meter *this,int x,int y,int w);
void SingleColCPUsMeter_draw(Meter *this,int x,int y,int w);
void DynamicMeter_updateValues_lto_priv_0(void);
void DynamicMeter_display(Meter_ *cast,RichString *out);
char * DynamicMeter_getCaption(Meter *this);
void CPUMeterCommonUpdateMode(Meter *this,int mode,int ncol);
void SingleColCPUsMeter_updateMode(Meter *this,int mode);
void DualColCPUsMeter_updateMode(Meter *this,int mode);
void QuadColCPUsMeter_updateMode(Meter *this,int mode);
void OctoColCPUsMeter_updateMode(Meter *this,int mode);
void AllCPUsMeter_done(Meter *this);
void insert(Hashtable *this,ht_key_t key,void *value);
Htop_Reaction actionHigherPriority(State_2 *st);
Htop_Reaction actionLowerPriority(State_2 *st);
Htop_Reaction actionRedraw(State_2 *st);
Htop_Reaction actionHelp(State_2 *st);
void ClockMeter_updateValues(Meter *this);
void DateMeter_updateValues(Meter *this);
void DateTimeMeter_updateValues(Meter *this);
void print_backtrace(void);
_Bool Action_setUserOnly(char *userName,uid_t *userId);
Htop_Reaction Action_setSortKey(Settings_2 *settings,ProcessField sortKey);
void * Hashtable_get(Hashtable *this,ht_key_t key);
Htop_Reaction Action_setScreenTab(State_2 *st,int x);
void Affinity_delete(Affinity *this);
Affinity_2 * Affinity_rowGet(Process_ *row,Machine *host);
void Hashtable_foreach(Hashtable *this,Hashtable_PairFunction f,void *userData);
void CRT_setMouse(_Bool enabled);
void CRT_enableDelay(void);
int CRT_readKey(void);
void Action_setBindings(Htop_Action_2 *keys);
_Bool Affinity_rowSet(Process_ *row,Arg arg);
char * DynamicColumn_name(uint key);
Hashtable_2 * DynamicMeters_new(void);
int Compat_faccessat(int dirfd,char *pathname,int mode,int flags);
int Compat_fstatat(int dirfd,char *dirpath,char *pathname,struct stat *statbuf,int flags);
ssize_t Compat_readlinkat(int dirfd,char *dirpath,char *pathname,char *buf,size_t bufsize);
_Bool String_startsWith(char *s,char *match);
void CRT_resetSignalHandlers(void);
void CRT_done(void);
void CRT_handleSIGTERM(int sgn);
void CRT_fatalError(char *note);
void CRT_disableDelay(void);
void CRT_setColors(int colorScheme);
HandlerResult ColorsPanel_eventHandler(ColorsPanel_ *super,int ch);
void CRT_init(Settings *settings,_Bool allowUnicode,_Bool retainScreenOnExit);
void DynamicColumn_done(DynamicColumn *this);
DynamicColumn_2 * DynamicColumn_search(Hashtable_2 *dynamics,char *name,uint *key);
DynamicColumn_2 * DynamicColumn_lookup(Hashtable_2 *dynamics,uint key);
_Bool DynamicColumn_writeField(Process_2 *proc,RichString *str,uint key);
_Bool DynamicMeter_search(Hashtable_2 *dynamics,char *name,uint *key);
char * DynamicMeter_lookup(Hashtable_2 *dynamics,uint key);
undefined8 DynamicScreens_new(void);
void DynamicScreen_done(DynamicScreen *this);
_Bool DynamicScreen_search(Hashtable_2 *screens,char *name,ht_key_t *key);
long DynamicScreen_lookup(ulong *param_1,uint param_2);
void FunctionBar_delete(FunctionBar *this);
int FunctionBar_drawExtra(FunctionBar *this,char *buffer,int attr,_Bool setCursor);
int FunctionBar_draw(FunctionBar *this);
void FunctionBar_append(char *buffer,int attr);
int FunctionBar_synthesizeEvent(FunctionBar *this,int pos);
void Hashtable_clear(Hashtable *this);
void Hashtable_delete(Hashtable *this);
void DynamicColumns_delete(Hashtable_2 *dynamics);
void DynamicMeters_delete(Hashtable *param_1);
void DynamicScreens_delete(Hashtable *param_1);
void AvailableColumnsPanel_delete(AvailableColumnsPanel_ *object);
void MaskItem_delete(MaskItem_ *cast);
void AffinityPanel_delete(AffinityPanel_ *cast);
void AvailableMetersPanel_delete(AvailableMetersPanel_ *object);
void CategoriesPanel_delete(void *param_1);
void ColorsPanel_delete(void *param_1);
void ColumnsPanel_delete(void *param_1);
void CommandScreen_delete(Object *this);
void DisplayOptionsPanel_delete(void *param_1);
Object * Action_pickFromVector(State_2 *st,MainPanel_ *list,int x,_Bool follow);
Affinity_2 * Affinity_new(Machine *host);
void Affinity_add(Affinity *this,uint id);
Affinity * AffinityPanel_getAffinity(AffinityPanel_ *super,Machine_2 *host);
void ColumnsPanel_update(ColumnsPanel_ *super);
Hashtable_2 * DynamicColumns_new(void);
FunctionBar * FunctionBar_new(char **functions,char **keys,int *events);
FunctionBar * FunctionBar_newEnterEsc(char *enter,char *esc);
void FunctionBar_setLabel(FunctionBar *this,int event,char *text);
Hashtable * Hashtable_new(size_t size,_Bool owner);
void Hashtable_setSize(Hashtable *this,size_t size);
void __thiscall Hashtable_setSize_118260(void *this,size_t size);
void Hashtable_put(Hashtable *this,ht_key_t key,void *value);
void * Hashtable_remove(Hashtable *this,ht_key_t key);
Header_4 * Header_new(Machine_2 *host,HeaderLayout hLayout);
Htop_Reaction actionSetSortColumn(State_2 *st);
Htop_Reaction actionExpandCollapseOrSortColumn(State_2 *st);
CategoriesPanel * CategoriesPanel_new(ScreenManager_3 *scr,Header_4 *header,Machine_2 *host);
ColorsPanel * ColorsPanel_new(Settings *settings);
void CategoriesPanel_makeColorsPage(CategoriesPanel *this);
DisplayOptionsPanel * DisplayOptionsPanel_new(Settings_4 *settings,ScreenManager_3 *scr);
void CategoriesPanel_makeDisplayOptionsPage(CategoriesPanel *this);
Htop_Reaction actionToggleKernelThreads(State_2 *st);
Htop_Reaction actionToggleUserlandThreads(State_2 *st);
Htop_Reaction actionExpandOrCollapseAllBranches(State_2 *st);
Htop_Reaction actionIncFilter(State_2 *st);
Htop_Reaction actionIncSearch(State_2 *st);
Htop_Reaction actionSetSchedPolicy(State_2 *st);
Htop_Reaction actionKill(State_2 *st);
HandlerResult AvailableColumnsPanel_eventHandler(AvailableColumnsPanel_ *super,int ch);
Htop_Reaction actionFilterByUser(State_2 *st);
Htop_Reaction actionSetup(State_2 *st);
Htop_Reaction actionLsof(State_2 *st);
Htop_Reaction actionShowLocks(State_2 *st);
Htop_Reaction actionStrace(State_2 *st);
EnvScreen * EnvScreen_new(Process_2 *process);
Htop_Reaction actionShowEnvScreen(State_2 *st);
CommandScreen * CommandScreen_new(Process *process);
Htop_Reaction actionShowCommandScreen(State_2 *st);
void MaskItem_display(MaskItem_ *cast,RichString *out);
void AffinityPanel_update(AffinityPanel *this,_Bool keepSelected);
HandlerResult AffinityPanel_eventHandler(AffinityPanel_ *super,int ch);
void ColumnsPanel_fill(ColumnsPanel *this,ScreenSettings *ss,Hashtable_2 *columns);
ColumnsPanel * ColumnsPanel_new(ScreenSettings *ss,Hashtable_2 *columns,_Bool *changed);
Panel * AffinityPanel_new(Machine_2 *host,Affinity *affinity,int *width);
Htop_Reaction actionSetAffinity(State_2 *st);
void AvailableColumnsPanel_addDynamicColumn(ht_key_t key,void *value,void *data);
void AvailableColumnsPanel_addPlatformColumns(AvailableColumnsPanel *this);
void AvailableColumnsPanel_fill(AvailableColumnsPanel *this,char *dynamicScreen,Hashtable_2 *dynamicColumns);
AvailableColumnsPanel * AvailableColumnsPanel_new(Panel *columns,Hashtable_2 *dynamicColumns);
AvailableMetersPanel *AvailableMetersPanel_new(Machine_4 *host,Header_3 *header,size_t columns,MetersPanel **meterPanels,ScreenManager_2 *scr);
ssize_t Compat_readlink(openat_arg_t dirfd,char *pathname,char *buf,size_t bufsize);
void CPUMeter_init(Meter *this);
void CPUMeter_getUiName(Meter *this,char *buffer,size_t length);
void DynamicMeter_getUiName(Meter *this,char *name,size_t length);
HandlerResult AvailableMetersPanel_eventHandler(AvailableMetersPanel_ *super,int ch);
void CPUMeterCommonInit(Meter *this,int ncol);
void SingleColCPUsMeter_init(Meter *this);
void DualColCPUsMeter_init(Meter *this);
void QuadColCPUsMeter_init(Meter *this);
void OctoColCPUsMeter_init(Meter *this);
void BatteryMeter_updateValues(Meter *this);
void CategoriesPanel_makeMetersPage(CategoriesPanel *this);
void CategoriesPanel_makeScreensPage(CategoriesPanel *this);
void CategoriesPanel_makeHeaderOptionsPage(CategoriesPanel *this);
HandlerResult CategoriesPanel_eventHandler(CategoriesPanel_ *super,int ch);
HandlerResult ColumnsPanel_eventHandler(ColumnsPanel_ *super,int ch);
void CRT_handleSIGSEGV(int signal);
int CommandLine_run(int argc,char **argv);
void CommandScreen_scan(InfoScreen *this);
void CommandScreen_draw(InfoScreen *this);
void EnvScreen_draw(InfoScreen *this);
void CPUMeter_updateValues(Meter *this);
void CPUMeter_display(Meter_ *cast,RichString *out);
void FileDescriptorMeter_display(Meter_ *cast,RichString *out);
void DiskIOMeter_updateValues(Meter *this);
void DiskIOMeter_display(Object *cast,RichString *out);
HandlerResult DisplayOptionsPanel_eventHandler(DisplayOptionsPanel_ *super,int ch);
void EnvScreen_scan(InfoScreen *this);
void FileDescriptorMeter_updateValues(Meter *this);
char * IncSet_getListItemValue(Panel *panel,int i);
char * MainPanel_getValue(Panel *this,int i);
void MemorySwapMeter_updateValues(Meter *this);
void MemorySwapMeter_draw(Meter *this,int x,int y,int w);
void BlankMeter_updateValues(Meter *this);
void BlankMeter_display_lto_priv_0(void);
char * Process_rowGetSortKey(Process_ *super);
_Bool Process_rowIsHighlighted(Process_ *super);
_Bool Process_rowIsVisible(Process_ *super,Table_4 *table);
void ProcessTable_prepareEntries(ProcessTable_ *super);
void Row_display(Row_ *cast,RichString *out);
void ListItem_delete(ListItem_ *cast);
void Meter_delete(Meter_ *cast);
void MemorySwapMeter_done(Meter *this);
void OptionItem_delete(OptionItem_ *cast);
int ListItem_compare(void *cast1,void *cast2);
void TextItem_display(TextItem_ *cast,RichString *out);
void HostnameMeter_updateValues(Meter *this);
void ProcessTable_iterateEntries(ProcessTable_ *super);
void Header_reinit(Header *this);
void Header_draw(Header *this);
void Header_updateData(Header *this);
int Header_calculateHeight(Header *this);
_Bool Object_isA(Object *o,ObjectClass *klass);
int Panel_getSelectedIndex(Panel *this);
Object * Panel_get(Panel *this,int i);
void CheckItem_set(CheckItem *this,_Bool value);
void Panel_setHeader(Panel *this,char *header);
void TextMeterMode_draw(Meter *this,int x,int y,int w);
void LEDMeterMode_draw(Meter *this,int x,int y,int w);
void IncSet_reset(IncSet *this,IncType type);
void IncSet_setFilter(IncSet *this,char *filter);
void Panel_setSelected(Panel *this,int selected);
Object * Panel_getSelected(Panel *this);
int Panel_size(Panel *this);
void Panel_resize(Panel *this,int w,int h);
void Row_setPidColumnWidth(pid_t maxPid);
void Machine_done(Machine *this);
void Machine_setTablesPanel(Machine *this,Panel *panel);
void Machine_scanTables(Machine *this);
void Row_setUidColumnWidth(uid_t maxUid);
void Row_resetFieldWidths(void);
void Panel_setSelectionColor(Panel *this,ColorElements colorId);
int MainPanel_selectedRow(MainPanel *this);
_Bool MainPanel_foreachRow(MainPanel *this,MainPanel_foreachRowFn fn,Arg arg,_Bool *wasAnyTagged);
void MainPanel_setState(MainPanel *this,State *state);
void MainPanel_setFunctionBar(MainPanel *this,_Bool readonly);
void Meter_setMode(Meter *this,int modeIndex);
void MemorySwapMeter_updateMode(Meter *this,int mode);
void MetersPanel_setMoving(MetersPanel *this,_Bool moving);
void Panel_moveSelectedUp(Panel *this);
char * Process_getCommand(Process *this);
void ListItem_display(ListItem_ *cast,RichString *out);
void BarMeterMode_draw(Meter *this,int x,int y,int w);
_Bool CheckItem_get(CheckItem *this);
void CheckItem_toggle(CheckItem *this);
int NumberItem_get(NumberItem *this);
void NumberItem_decrease(NumberItem *this);
void NumberItem_increase(NumberItem *this);
void NumberItem_toggle(NumberItem *this);
void Panel_setCursorToSelection(Panel *this);
void Panel_move(Panel *this,int x,int y);
Object * Panel_remove(Panel *this,int i);
void Panel_moveSelectedDown(Panel *this);
_Bool Panel_onKey(Panel *this,int key);
int Panel_getCh(Panel *this);
void Process_fillStarttimeBuffer(Process *this);
void Process_writeCommand(Process *this,int attr,int baseAttr,RichString *str);
void Process_done(Process *this);
void Process_init(Process *this,Machine_3 *host);
void Row_init(Row *this,Machine_2 *host);
_Bool Process_rowSendSignal(Process_ *super,Arg sgn);
int Process_compareByKey_Base(Process_3 *p1,Process_3 *p2,ProcessField key);
int Process_compare(void *v1,void *v2);
int Process_compareByParent(Row_3 *r1,Row_3 *r2);
void Process_updateCPUFieldWidths(float percentage);
void Row_updateFieldWidth(RowField key,size_t width);
_Bool Process_setPriority(Process *this,int priority);
_Bool Process_rowChangePriorityBy(Process_ *super,Arg delta);
_Bool Process_rowSetPriority(Process_ *super,int priority);
Process_2 *ProcessTable_getProcess(ProcessTable *this,pid_t pid,_Bool *preExisting,Process_New constructor);
void Row_done(void);
void Header_delete(Header *this);
void Header_setLayout(Header *this,HeaderLayout hLayout);
ListItem * ListItem_new(char *value,int key);
void ListItem_init(ListItem *this,char *value,int key);
void ListItem_append(ListItem *this,char *text);
void Machine_populateTablesFromSettings(Machine *this,Settings_4 *settings,Table_2 *processTable);
Meter_3 * Meter_new(Machine_2 *host,uint param,MeterClass_3 *type);
Meter_3 * Header_addMeterByClass(Header *this,MeterClass_3 *type,uint param,uint column);
void MemorySwapMeter_init(Meter *this);
void Meter_setCaption(Meter *this,char *caption);
void GraphMeterMode_draw(Meter *this,int x,int y,int w);
TextItem * TextItem_new(char *text);
CheckItem * CheckItem_newByRef(char *text,_Bool *ref);
CheckItem * CheckItem_newByVal(char *text,_Bool value);
NumberItem * NumberItem_newByRef(char *text,int *ref,int scale,int min,int max);
NumberItem * NumberItem_newByVal(char *text,int value,int scale,int min,int max);
Panel * Panel_new(int x,int y,int w,int h,ObjectClass *type,_Bool owner,FunctionBar *fuBar);
void Panel_init(Panel *this,int x,int y,int w,int h,ObjectClass *type,_Bool owner,FunctionBar *fuBar);
HandlerResult Panel_selectByTyping(Panel *this,int ch);
void Process_makeCommandStr(Process *this,Settings_5 *settings);
void Process_updateComm(Process *this,char *comm);
void Process_updateCmdline(Process *this,char *cmdline,int basenameStart,int basenameEnd);
void Process_updateExe(Process *this,char *exe);
void Header_populateFromSettings(Header *this);
void Panel_prune(Panel *this);
void Header_writeBackToSettings(Header *this);
void Panel_done(Panel *this);
void HeaderOptionsPanel_delete_lto_priv_0(void *param_1);
void IncSet_delete(IncSet *this);
InfoScreen_2 * InfoScreen_done(InfoScreen *this);
void MainPanel_delete(MainPanel_ *object);
void MetersPanel_cleanup(void);
void MetersPanel_delete_lto_priv_0(void *param_1);
void Panel_delete(void *param_1);
HandlerResult HeaderOptionsPanel_eventHandler(HeaderOptionsPanel_ *super,int ch);
HeaderOptionsPanel * HeaderOptionsPanel_new(Settings_4 *settings,ScreenManager_3 *scr);
IncSet_3 * IncSet_new(FunctionBar *bar);
InfoScreen_2 *InfoScreen_init(InfoScreen *this,Process *process,FunctionBar *bar,int height,char *panelHeader);
OpenFilesScreen * OpenFilesScreen_new(Process *process);
ProcessLocksScreen * ProcessLocksScreen_new(Process_2 *process);
void IncSet_drawBar(IncSet *this,int attr);
void IncSet_activate(IncSet *this,IncType type,Panel *panel);
void Panel_draw(Panel *this,_Bool force_redraw,_Bool focus,_Bool highlightSelected,_Bool hideFunctionBar);
void InfoScreen_drawTitled(InfoScreen *this,char *fmt,...);
void OpenFilesScreen_draw(InfoScreen *this);
void ProcessLocksScreen_draw(InfoScreen *this);
_Bool Process_rowMatchesFilter(Process_ *super,Table_4 *table);
int IncSet_synthesizeEvent(IncSet *this,int x);
int Meter_humanUnit(char *buffer,double value,size_t size);
ListItem * Meter_toListItem(Meter *this,_Bool moving);
MetersPanel_2 *MetersPanel_new(Settings_4 *settings,char *header,Vector *meters,ScreenManager_3 *scr);
char * RowField_alignedTitle(Settings_4 *settings,RowField field);
RowField RowField_keyAt(Settings_4 *settings,int at);
void LoadAverageMeter_updateValues(Meter *this);
void LoadMeter_updateValues(Meter *this);
void LoadAverageMeter_display(Meter_ *cast,RichString *out);
void LoadMeter_display(Meter_ *cast,RichString *out);
void Machine_init(Machine *this,UsersTable *usersTable,uid_t userId);
void MainPanel_updateLabels(MainPanel *this,_Bool list,_Bool filter);
void MainPanel_drawFunctionBar(MainPanel_ *super,_Bool hideFunctionBar);
void MainPanel_printHeader(MainPanel_ *super);
MainPanel * MainPanel_new(void);
void MemoryMeter_updateValues(Meter *this);
void MemoryMeter_display(Meter_ *cast,RichString *out);
void NetworkIOMeter_display(Object *cast,RichString *out);
void CheckItem_display(CheckItem_ *cast,RichString *out);
void NumberItem_display(NumberItem_ *cast,RichString *out);
void Panel_insert(Panel *this,int i,Object *o);
HandlerResult MetersPanel_eventHandler(MetersPanel_ *super,int ch);
void NetworkIOMeter_updateValues(Meter *this);
void Panel_add(Panel *this,Object *o);
_Bool IncSet_handleKey(IncSet *this,int ch,Panel *panel,IncMode_GetPanelValue_2 getPanelValue,Vector *lines);
void InfoScreen_run(InfoScreen *this);
HandlerResult MainPanel_eventHandler(MainPanel_ *super,int ch);
void InfoScreen_addLine(InfoScreen *this,char *line);
void OpenFilesScreen_scan(InfoScreen_2 *super);
void InfoScreen_appendLine(InfoScreen *this,char *line);
void Panel_set(Panel *this,int i,Object *o);
void Panel_splice(Panel *this,Vector *from);
void Process_writeField(Process *this,RichString *str,RowField field);
void Process_rowWriteField(Process_ *super,RichString *str,RowField field);
void ProcessLocksScreen_scan(InfoScreen *this);
void ProcessTable_init(ProcessTable *this,ObjectClass *klass,Machine_2 *host,Hashtable_2 *pidMatchList);
void ProcessTable_done(ProcessTable *this);
void ProcessTable_cleanupEntries(Table_2 *super);
int Row_compare(void *v1,void *v2);
void Table_prepareEntries(Table *this);
void quickSort(Object **array,int left,int right,Object_Compare compare);
void ScreenListItem_delete(ScreenListItem_ *cast);
_Bool drawTab(int *y,int *x,int l,char *name,_Bool cur);
void startRenaming(ScreensPanel_ *super);
int toFieldIndex(Hashtable_2 *columns,char *str);
void writeFields(FILE *fd,ProcessField *fields,Hashtable_2 *columns,_Bool byName,char separator);
void SysArchMeter_updateValues(Meter *this);
void Row_toggleTag(Row *this);
int Row_compareByParent_Base(void *v1,void *v2);
int compareRowByKnownParentThenNatural(void *v1,void *v2);
void RichString_setAttrn(RichString *this,int attrs,int start,int charcount);
int RichString_findChar(RichString *this,char c,int start);
void RichString_delete(RichString *this);
void RichString_setAttr(RichString *this,int attrs);
_Bool Scheduling_rowSetPolicy(Process_ *row,Arg arg);
char * Scheduling_formatPolicy(int policy);
void Scheduling_readProcessPolicy(Process *proc);
int ScreenManager_size(ScreenManager *this);
Object * Vector_remove(Vector *this,int idx);
void ScreenManager_resize(ScreenManager *this);
void ScreenSettings_delete(ScreenSettings *this);
void Vector_moveUp(Vector *this,int idx);
void Settings_delete(Settings *this);
void String_freeArray(char **s);
void ScreenSettings_invertSortOrder(ScreenSettings *this);
void ScreenSettings_setSortKey(ScreenSettings *this,ProcessField sortKey);
void Settings_enableReadonly(void);
_Bool Settings_isReadonly(void);
void Table_setPanel(Table *this,Panel *panel);
Object * Vector_softRemove(Vector *this,int idx);
void Vector_quickSortCustomCompare(Vector *this,Object_Compare compare);
void Table_expandTree(Table *this);
void UsersTable_foreach(UsersTable *this,Hashtable_PairFunction f,void *userData);
void Vector_delete(Vector *this);
void ScreenManager_delete(ScreenManager *this);
void Vector_prune(Vector *this);
void Vector_insertionSort(Vector *this);
Object * Vector_take(Vector *this,int idx);
Panel * ScreenManager_remove(ScreenManager *this,int idx);
void Vector_compact(Vector *this);
void Vector_moveDown(Vector *this,int idx);
int Vector_indexOf(Vector *this,void *search_,Object_Compare compare);
int Row_printPercentage(float val,char *buffer,size_t n,uint8_t width,int *attr);
void TasksMeter_updateValues(Meter *this);
_Bool TraceScreen_forkTracer(TraceScreen *this);
void ScreensPanel_delete(Panel_ *object);
void ScreenTabsPanel_delete_lto_priv_0(void *param_1);
void ScreenNamesPanel_delete(ScreenNamesPanel_ *object);
void TraceScreen_delete(TraceScreen_ *cast);
int Settings_write(Settings *this,_Bool onCrash);
void SwapMeter_updateValues(Meter *this);
void Table_done(Table *this);
void Table_delete(Table_ *cast);
void UsersTable_delete(UsersTable *this);
void Table_removeIndex(Table *this,Row_2 *row,int idx);
void Table_cleanupRow(Table_2 *table,Row_2 *row,int idx);
void Table_cleanupEntries(Table *this);
void TraceScreen_draw(InfoScreen *this);
void TraceScreen_updateTrace(TraceScreen_ *super);
_Bool TraceScreen_onKey(TraceScreen_ *super,int ch);
void UptimeMeter_updateValues(Meter *this);
void fail(void);
void * xRealloc(void *ptr,size_t size);
void * xMalloc(size_t size);
void RichString_setLen(RichString *this,int len);
void RichString_appendChr(RichString *this,int attrs,char c,int count);
void RichString_rewind(RichString *this,int count);
int RichString_appendnWideColumns(RichString *this,int attrs,char *data_c,int len,int *columns);
void Row_printLeftAlignedField(RichString *str,int attr,char *content,uint width);
int RichString_appendWide(RichString *this,int attrs,char *data);
int RichString_appendnWide(RichString *this,int attrs,char *data,int len);
int RichString_writeWide(RichString *this,int attrs,char *data);
int RichString_appendAscii(RichString *this,int attrs,char *data);
int RichString_appendnAscii(RichString *this,int attrs,char *data,int len);
void Row_printKBytes(RichString *str,ulonglong number,_Bool coloring);
void Row_printBytes(RichString *str,ulonglong number,_Bool coloring);
void Row_printCount(RichString *str,ulonglong number,_Bool coloring);
void Row_printTime(RichString *str,ulonglong totalHundredths,_Bool coloring);
void Row_printRate(RichString *str,double rate,_Bool coloring);
void TasksMeter_display(Meter_ *cast,RichString *out);
int RichString_writeAscii(RichString *this,int attrs,char *data);
void SwapMeter_display(Meter_ *cast,RichString *out);
void Table_printHeader(Settings_4 *settings,RichString *header);
void Scheduling_togglePolicyPanelResetOnFork(Panel *schedPanel);
void * xCalloc(size_t nmemb,size_t size);
ScreenManager_3 * ScreenManager_new(Header_4 *header,Machine_2 *host,State *state,_Bool owner);
ScreenListItem * ScreenListItem_new(char *value,ScreenSettings_4 *ss);
void ScreensPanel_update(ScreensPanel_ *super);
ScreenNameListItem * ScreenNameListItem_new(char *value,ScreenSettings_4 *ss);
void Settings_defaultMeters(Settings *this,uint initialCpuCount);
void * xReallocArray(void *ptr,size_t nmemb,size_t size);
void Settings_setHeaderLayout(Settings *this,HeaderLayout hLayout);
Table_2 * Table_init(Table *this,ObjectClass *klass,Machine_2 *host);
TraceScreen * TraceScreen_new(Process *process);
UsersTable * UsersTable_new(void);
char * UsersTable_getRef(UsersTable *this,uint uid);
Vector * Vector_new(ObjectClass *type,_Bool owner,int size);
void * xMallocArray(size_t nmemb,size_t size);
void * xReallocArrayZero(void *ptr,size_t prevmemb,size_t newmemb,size_t size);
void Vector_insert(Vector *this,int idx,void *data_);
void ScreenManager_insert(ScreenManager *this,Panel *item,int size,int idx);
void ScreenManager_add(ScreenManager *this,Panel *item,int size);
void Vector_set(Vector *this,int idx,void *data_);
Panel * Scheduling_newPolicyPanel(int preSelectedPolicy);
Panel * Scheduling_newPriorityPanel(int policy,int preSelectedPriority);
ScreensPanel * ScreensPanel_new(Settings_3 *settings);
ScreenNamesPanel * ScreenNamesPanel_new(Settings_3 *settings);
ScreenTabsPanel * ScreenTabsPanel_new(Settings_3 *settings);
Panel * SignalsPanel_new(int preSelectedSignal);
void Table_add(Table *this,Row_2 *row);
void Table_buildTreeBranch(Table *this,int rowid,uint level,int32_t indent,_Bool show);
void Table_buildTree(Table *this);
void Table_collapseAllBranches(Table *this);
void Table_updateDisplayList(Table *this);
void Table_rebuildPanel(Table *this);
void ScreenManager_run(ScreenManager *this,Panel **lastFocus,int *lastKey,char *name);
void Vector_add(Vector *this,void *data_);
void Vector_splice(Vector *this,Vector *from);
char * String_cat(char *s1,char *s2);
char * String_trim(char *in);
char ** String_split(char *s,char sep,size_t *n);
void Settings_readMeters(Settings *this,char *line,uint column);
void Settings_readMeterModes(Settings *this,char *line,uint column);
void ScreenSettings_readFields(ScreenSettings_4 *ss,Hashtable_2 *columns,char *line);
ScreenSettings_4 * Settings_initScreenSettings(ScreenSettings_4 *ss,Settings_3 *this,char *columns);
ScreenSettings_4 * Settings_newScreen(Settings *this,ScreenDefaults *defaults);
HandlerResult ScreensPanel_eventHandler(ScreensPanel_ *super,int ch);
ScreenSettings_4 *Settings_newDynamicScreen(Settings *this,char *tab,DynamicScreen *screen,Table_3 *table);
HandlerResult ScreenNamesPanel_eventHandlerNormal(ScreenNamesPanel_ *super,int ch);
HandlerResult ScreenTabsPanel_eventHandler(ScreenTabsPanel_ *super,int ch);
HandlerResult ScreenNamesPanel_eventHandler(ScreenNamesPanel_ *super,int ch);
_Bool String_contains_i(char *s1,char *s2,_Bool multi);
char * String_readLine(FILE *fd);
_Bool Settings_read(Settings *this,char *fileName,uint initialCpuCount);
Settings_3 *Settings_new(uint initialCpuCount,Hashtable_2 *dynamicMeters,Hashtable_2 *dynamicColumns,Hashtable_2 *dynamicScreens);
_Bool StrBuf_putc_count(StrBuf_state *p,char c);
_Bool StrBuf_putc_write(StrBuf_state *p,char c);
int sortTtyDrivers(void *va,void *vb);
void Process_delete(LinuxProcess_ *cast);
void SystemdMeter_done(Meter *this);
void scanCPUFrequencyFromCPUinfo(LinuxMachine *this);
_Bool LinuxProcessTable_readStatusFile(LinuxProcess_ *process,openat_arg_t procFd);
void LinuxProcessTable_readOomData(LinuxProcess *process,openat_arg_t procFd);
_Bool CGroup_filterName_internal(char *cgroup,StrBuf_state *s,StrBuf_putc_t w);
_Bool CGroup_filterContainer_internal(char *cgroup,StrBuf_state *s,StrBuf_putc_t w);
int handleNetlinkMsg(nl_msg *nlmsg,void *linuxProcess);
size_t String_safeStrncpy(char *dest,char *src,size_t size);
ssize_t readfd_internal(int fd,void *buffer,size_t count);
ACPresence procAcpiCheck(void);
void Platform_Battery_getSysData(double *percent,ACPresence *isOnAC);
ssize_t xReadfile(char *pathname,void *buffer,size_t count);
ssize_t xReadfileat(openat_arg_t dirfd,char *pathname,void *buffer,size_t count);
ssize_t full_write(int fd,void *buf,size_t count);
int compareRealNumbers(double a,double b);
double sumPositiveValues(double *array,size_t count);
void Generic_gettime_realtime(timeval *tvp,uint64_t *msec);
void Generic_gettime_monotonic(uint64_t *msec);
void Generic_hostname(char *buffer,size_t size);
IOPriority IOPriorityPanel_getIOPriority(Panel *this);
int LibSensors_init(void);
void LibSensors_cleanup(void);
int LibSensors_reload(void);
void Machine_delete(LinuxMachine_ *super);
_Bool Machine_isCPUonline(LinuxMachine_ *super,uint id);
IOPriority LinuxProcess_updateIOPriority(LinuxProcess_ *p);
_Bool LinuxProcess_rowSetIOPriority(Process_ *super,Arg ioprio);
_Bool LinuxProcess_isAutogroupEnabled(void);
void Platform_setBindings(Htop_Action_2 *keys);
int Platform_getUptime(void);
void Platform_getLoadAverage(double *one,double *five,double *fifteen);
pid_t Platform_getMaxPid(void);
double Platform_setCPUValues(Meter *this,uint cpu);
void Platform_setMemoryValues(Meter *this);
void Platform_setSwapValues(Meter *this);
void Platform_setZramValues(Meter *this);
void Platform_setZfsArcValues(Meter *this);
void ZfsArcMeter_readStats(Meter *this,ZfsArcStats *stats);
void Platform_setZfsCompressedArcValues(Meter *this);
void ZfsCompressedArcMeter_readStats(Meter *this,ZfsArcStats *stats);
void Platform_getFileDescriptors(double *used,double *max);
_Bool Platform_getDiskIO(DiskIOData *data);
_Bool Platform_getNetworkIO(NetworkIOData *data);
void Platform_longOptionsUsage(void);
CommandLineStatus Platform_getLongOption(int opt,int argc,char **argv);
void Platform_done(void);
_Bool Platform_init(void);
_Bool Platform_init_13caa0(void);
int xAsprintf(char **strp,char *fmt,...);
int xSnprintf(char *buf,size_t len,char *fmt,...);
void Platform_getPressureStall(char *file,_Bool some,double *ten,double *sixty,double *threehundred);
double Platform_Battery_getProcBatInfo(void);
void Platform_getBattery(double *percent,ACPresence *isOnAC);
void PressureStallMeter_updateValues(Meter *this);
void SELinuxMeter_updateValues(Meter *this);
void ZfsCompressedArcMeter_updateValues(Meter *this);
_Bool LinuxProcessTable_readStatFile(LinuxProcess *lp,openat_arg_t procFd,LinuxMachine_2 *lhost,_Bool scanMainThread,char *command,size_t commLen);
_Bool LinuxProcess_changeAutogroupPriorityBy(Process_3 *p,Arg delta);
_Bool LinuxProcess_rowChangeAutogroupPriorityBy(Process_ *super,Arg delta);
Htop_Reaction Platform_actionHigherAutogroupPriority(State_2 *st);
Htop_Reaction Platform_actionLowerAutogroupPriority(State_2 *st);
char * xStrdup(char *str);
void free_and_xStrdup(char **ptr,char *str);
char * xStrndup(char *str,size_t len);
char * CGroup_filterName(char *cgroup);
char * CGroup_filterContainer(char *cgroup);
void LibSensors_getCPUTemperatures(CPUData *cpus,uint existingCPUs,uint activeCPUs);
Process_3 * LinuxProcess_new(Machine_3 *host);
void LinuxProcessTable_initTtyDrivers(LinuxProcessTable *this);
void LinuxProcessTable_readCGroupFile(LinuxProcess *process,openat_arg_t procFd);
void LinuxProcessTable_readSecattrData(LinuxProcess *process,openat_arg_t procFd);
void LinuxProcessTable_readCwd(LinuxProcess *process,openat_arg_t procFd);
char * Platform_getProcessEnv(pid_t pid);
FileLocks_ProcessData * Platform_getProcessLocks(pid_t pid);
void SystemdMeter_updateValues(Meter *this);
Affinity_2 * Affinity_get(Process *p,Machine *host);
char * Generic_uname(void);
char * Generic_uname_1406b0(void);
void HugePageMeter_updateValues(Meter *this);
void ZramMeter_updateValues(Meter *this);
void ZfsArcMeter_updateValues(Meter *this);
void HugePageMeter_display(Meter_ *cast,RichString *out);
void ZramMeter_display(Meter_ *cast,RichString *out);
void ZfsArcMeter_display(Meter_ *cast,RichString *out);
Panel * IOPriorityPanel_new(IOPriority currPrio);
void LinuxMachine_updateCPUcount(LinuxMachine *this);
void LinuxMachine_scanCPUTime(LinuxMachine *this);
void Machine_scan(LinuxMachine_ *super);
Machine_2 * Machine_new(UsersTable *usersTable,uid_t userId);
void LinuxProcess_rowWriteField(LinuxProcess_ *super,RichString *str,ProcessField field);
int LinuxProcess_compareByKey(LinuxProcess_ *v1,LinuxProcess_ *v2,ProcessField key);
ProcessTable_2 * ProcessTable_new(Machine_2 *host,Hashtable_2 *pidMatchList);
void ProcessTable_delete(LinuxProcessTable_ *cast);
_Bool LinuxProcessTable_readCmdlineFile(Process_2 *process,openat_arg_t procFd);
Htop_Reaction Platform_actionSetIOPriority(State_2 *st);
void PressureStallMeter_display(Meter_ *cast,RichString *out);
void ZfsCompressedArcMeter_display(Meter_ *cast,RichString *out);
void _SystemdMeter_display(Object *cast,RichString *out,SystemdMeterContext_t *ctx);
void SystemdMeter_display(Object *cast,RichString *out);
void SystemdUserMeter_display(Object *cast,RichString *out);
_Bool LinuxProcessTable_recurseProcTree(LinuxProcessTable *this,openat_arg_t parentFd,LinuxMachine_2 *lhost,char *dirname,Process_2 *parent);
void ProcessTable_goThroughEntries(LinuxProcessTable_ *super);
void EnvScreen_delete(Object *this);  /* alias of CommandScreen_delete */
void OpenFilesScreen_delete(Object *this);  /* alias of CommandScreen_delete */
void ProcessLocksScreen_delete(Object *this);  /* alias of CommandScreen_delete */
