/* Prototypes for imported functions Ghidra has no signature for (applied by ApplyFixes.java).
   Opaque pointers are void *, size_t is unsigned long. */
int backtrace(void **buffer, int size);
void backtrace_symbols_fd(void **buffer, int size, int fd);
int beep(void);
int cbreak(void);
int curs_set(int visibility);
int define_key(char *definition, int keycode);
int dlclose(void *handle);
char *dlerror(void);
void *dlopen(char *filename, int flags);
void *dlsym(void *handle, char *symbol);
int endwin(void);
long __fdelt_chk(long d);
char *__fgets_chk(char *buf, unsigned long size, int n, void *stream);
int __fprintf_chk(void *stream, int flag, char *format, ...);
unsigned long __fread_chk(void *ptr, unsigned long ptrlen, unsigned long size, unsigned long n, void *stream);
int genl_ctrl_resolve(void *sk, char *name);
int genlmsg_parse(void *nlh, int hdrlen, void **tb, int maxtype, void *policy);
void *genlmsg_put(void *msg, unsigned int port, unsigned int seq, int family, int hdrlen, int flags, unsigned char cmd, unsigned char version);
int getmouse(void *event);
int getopt_long(int argc, char **argv, char *optstring, void *longopts, int *longindex);
int halfdelay(int tenths);
int has_colors(void);
int init_pair(short pair, short f, short b);
void *initscr(void);
int intrflush(void *win, int bf);
int __isoc23_fscanf(void *stream, char *format, ...);
int __isoc23_sscanf(char *str, char *format, ...);
long __isoc23_strtol(char *nptr, char **endptr, int base);
long __isoc23_strtoll(char *nptr, char **endptr, int base);
unsigned long __isoc23_strtoul(char *nptr, char **endptr, int base);
unsigned long __isoc23_strtoull(char *nptr, char **endptr, int base);
int keypad(void *win, int bf);
unsigned long __mbstowcs_chk(int *dst, char *src, unsigned long len, unsigned long dstlen);
void *__memcpy_chk(void *dest, void *src, unsigned long len, unsigned long destlen);
void *__memmove_chk(void *dest, void *src, unsigned long len, unsigned long destlen);
void *__memset_chk(void *dest, int c, unsigned long len, unsigned long destlen);
int mouseinterval(int erval);
unsigned long mousemask(unsigned long newmask, unsigned long *oldmask);
int mvcur(int oldrow, int oldcol, int newrow, int newcol);
int napms(int ms);
void *nla_data(void *nla);
void *nla_next(void *nla, int *remaining);
int nla_put_u32(void *msg, int attrtype, unsigned int value);
void nl_close(void *sk);
int nl_connect(void *sk, int protocol);
void *nlmsg_alloc(void);
void nlmsg_free(void *msg);
void *nlmsg_hdr(void *msg);
int nl_recvmsgs_default(void *sk);
int nl_send_sync(void *sk, void *msg);
void *nl_socket_alloc(void);
void nl_socket_free(void *sk);
int nl_socket_modify_cb(void *sk, int type, int kind, void *func, void *arg);
int nocbreak(void);
int nodelay(void *win, int bf);
int noecho(void);
int nonl(void);
int __printf_chk(int flag, char *format, ...);
long __read_chk(int fd, void *buf, unsigned long nbytes, unsigned long buflen);
int set_escdelay(int ms);
int __snprintf_chk(char *s, unsigned long maxlen, int flag, unsigned long slen, char *format, ...);
int start_color(void);
char *__stpcpy_chk(char *dest, char *src, unsigned long destlen);
char *__strncat_chk(char *s1, char *s2, unsigned long n, unsigned long s1len);
int tputs(char *str, int affcnt, void *putc);
int use_default_colors(void);
int __vasprintf_chk(char **result_ptr, int flag, char *format, void *ap);
int __vsnprintf_chk(char *s, unsigned long maxlen, int flag, unsigned long slen, char *format, void *ap);
int waddch(void *win, unsigned int ch);
int waddnstr(void *win, char *str, int n);
int wadd_wch(void *win, void *wch);
int wadd_wchnstr(void *win, void *wchstr, int n);
int wattr_off(void *win, unsigned int attrs, void *opts);
int wattr_on(void *win, unsigned int attrs, void *opts);
int wattrset(void *win, int attrs);
int wclear(void *win);
int wgetch(void *win);
int whline(void *win, unsigned int ch, int n);
int wmove(void *win, int y, int x);
int wrefresh(void *win);
int wvline(void *win, unsigned int ch, int n);
